name: markup_analyzer
description: This tool checks the markup of a Flutter project and generates a report.
version: 3.1.0

homepage: https://www.contributors.info/repository/markup_analyzer

repository: https://github.com/AlexHCJP/markup_analyzer

issue_tracker: https://github.com/AlexHCJP/markup_analyzer/issues

topics:
  - analyzer
  - linter
  - script
  - code-style
  - format

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  collection: ^1.19.1
  custom_lint_builder: ^0.8.1
  

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0

