name: markup_analyzer
description: This tool checks the markup of a Flutter project and generates a report.
version: 1.0.4
homepage: https://github.com/AlexHCJP/markup_analyzer

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
