name: markup_analyzer
description: This tool checks the markup of a Flutter project and generates a report.
version: 2.0.0

homepage: https://www.contributors.info/repository/markup_analyzer
repository: https://github.com/AlexHCJP/markup_analyzer


topics:
  - analyzer
  - linter
  - script
  - code-style
  - format

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
