name: test_localization
description: This tool checks if there are any untranslated strings in your presentation layer.
version: 1.0.1
homepage: https://github.com/AlexHCJP/test_localization

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
