name: markup_analyzer
description: This tool checks the markup of a Flutter project and generates a report.
version: 3.0.0

homepage: https://www.contributors.info/repository/markup_analyzer

repository: https://github.com/AlexHCJP/markup_analyzer

issue_tracker: https://github.com/AlexHCJP/markup_analyzer/issues

topics:
  - analyzer
  - linter
  - script
  - code-style
  - format

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^7.4.5
  analyzer_plugin: ^0.13.1
  collection: ^1.19.1
  custom_lint_builder: ^0.7.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

