name: markup_analyzer
description: This tool checks the markup of a Flutter project and generates a report.
version: 4.0.0

homepage: https://github.com/AlexHCJP/markup_analyzer
repository: https://github.com/AlexHCJP/markup_analyzer
issue_tracker: https://github.com/AlexHCJP/markup_analyzer/issues

topics:
  - analyzer
  - linter
  - script
  - code-style
  - format

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  analysis_server_plugin: ^0.3.15
  analyzer: ^13.0.0
  analyzer_plugin: ^0.14.9

